# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- master
- release
- develop

variables:
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  CDP_BUILD_TAG: azurerecoverytools

stages:
- stage: build
  jobs:

  # Windows build job
  - job: windows_build
    pool:
      demands:
      - msbuild
      - visualstudio
      vmImage: windows-latest
      type: windows-latest

    variables:
      WindowsContainerImage: 'cdpxwin1809.azurecr.io/global/vse2019:latest'
      ob_outputDirectory: '$(Build.SourcesDirectory)\Out'
      ob_symbolsPublishing_enabled: true
      ob_symbolsPublishing_symbolsFolder: '$(REPOROOT)\Symbols'

    steps:
      # Restore host NuGet packages.
      - task: NuGetCommand@2
        displayName: 'Restore Host NuGet Packages'
        inputs:
          command: 'restore'
          restoreSolution: '$(REPOROOT)\host\host.sln'
          feedsToUse: 'config'
          nugetConfigPath: '$(REPOROOT)\.config\NuGet.config'

      # Build AzureRecoveryUtil.exe.
      - task: MSBuild@1
        displayName: 'Build AzureRecoveryUtil.exe'
        inputs: 
          solution: '$(REPOROOT)\host\host.sln'
          msbuildLocationMethod: 'location'
          msbuildLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
          platform: 'win32'
          configuration: 'release'
          msbuildArguments: '-t:AzureRecoveryUtil /v:n /nr:false /flp1:Verbosity=n;LogFile=$(OUTPUTROOT)\logs\AzureRecoveryUtil.log;Encoding=UTF-8 /flp2:logfile=$(OUTPUTROOT)\logs\AzureRecoveryUtil.err;errorsonly /p:Configuration="LIB release - LIB OpenSSL"'
          clean: false
          maximumCpuCount: true
          logProjectEvents: true

      # Copy build artifacts.
      - task: PowerShell@2
        displayName: 'Copy Build Artifacts'
        inputs:
          targetType: 'inline'
          script: |
            Copy-Item -Path $(REPOROOT)\host\AzureRecoveryUtil\Release\AzureRecoveryUtil.exe $(OUTPUTROOT)\
            Copy-Item -Path $(REPOROOT)\host\AzureRecoveryUtil\Release\AzureRecoveryUtil.pdb $(OUTPUTROOT)\
          workingDirectory: '$(REPOROOT)'

      # Capture symbol files.
      - task: PowerShell@2
        displayName: 'Capture Symbol Files'
        inputs:
          targetType: 'inline'
          script: |
            New-Item -Path $(REPOROOT) -Name "Symbols" -ItemType "Directory" -Force
            Copy-Item -Path $(REPOROOT)\host\AzureRecoveryUtil\Release\AzureRecoveryUtil.pdb $(REPOROOT)\Symbols

  # Linux build job.
  - job: linux_build
    pool:
      vmImage: ubuntu-latest
      type: linux

    variables:
      LinuxContainerImage: 'cdpxlinux.azurecr.io/user/asr-inmage-srcteam/ubuntu-16.04:latest'
      ob_outputDirectory: '$(Build.SourcesDirectory)/out'
      ob_linuxSymbolsPublishing_enabled: true
      ob_linuxSymbolsPublishing_symbolsFolder: '$(REPOROOT)/Symbols'

    steps:
      # install g++ and ncurses-devel
      - task: CmdLine@2
        inputs:
          script: |
            sudo apt-get install make

            sudo apt-get install g++

            sudo apt-get install build-essential

            sudo apt-get install libncurses-dev

            sudo apt-get install uuid-dev

            sudo ln -s -T /usr/bin/make /usr/bin/gmake
          failOnStderr: true

      # Build AzureRecoveryUtil binary.
      - task: Bash@3
        displayName: 'Build AzureRecoveryUtil Binary'
        inputs:
          filePath: '$(REPOROOT)/.pipelines/BuildAzureRecoveryUtil.sh'
          failOnStderr: true

      # Capature symbols for publishing.
      - task: Bash@3
        displayName: 'Capature Symbols For Publishing'
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p $(REPOROOT)/Symbols
            cp -f $(REPOROOT)/host/Linux_x86_64/AzureRecoveryUtil/release/AzureRecoveryUtil $(REPOROOT)/Symbols
            cp -f $(REPOROOT)/host/Linux_x86_64/AzureRecoveryUtil/release/AzureRecoveryUtil.dbg $(REPOROOT)/Symbols
          failOnStderr: true

      # Copy build artifacts.
      - task: Bash@3
        displayName: 'Copy Build Artifacts'
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p $(Build.SourcesDirectory)/out/logs
            cp -f $(REPOROOT)/host/Linux_x86_64/AzureRecoveryUtil/release/AzureRecoveryUtil $(Build.SourcesDirectory)/out
            cp -f $(REPOROOT)/host/Linux_x86_64/AzureRecoveryUtil/release/AzureRecoveryUtil.dbg $(Build.SourcesDirectory)/out
            cp -f $(REPOROOT)/host/AzureRecoveryUtil/Scripts/linux/{*.sh,network,CentOS-Base.repo} $(Build.SourcesDirectory)/out
            cp -f $(REPOROOT)/thirdparty/setuptools-33.1.1/{*.py,*.zip} $(Build.SourcesDirectory)/out
            cp -f $(REPOROOT)/host/AzureRecoveryUtilBuild.log $(Build.SourcesDirectory)/out/logs
          failOnStderr: true

